version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
    ports:
      - 5430:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
